### ISSUE TITLE
cache issue? `error: hash mismatch importing path`

### ISSUE THREAD

**Issue by srid** [garnix-io/issues#44] opened 2022-12-19 16:37 UTC
https://github.com/EmaApps/ema-template/actions/runs/3733203286/jobs/6333727221

I tried restarting the build, but the error occurs on a different derivation.

```
error: hash mismatch importing path '/nix/store/x3xa7h9wg6phf5a83is1vp4a663c61sq-auto-update-0.1.6';
         specified: sha256:0ylfgvbw5v9v0z5mzfa139zc96qkncp2lc4ri65pbk74zla09xyb
         got:       sha256:1rsprx5vgsidjil565s12nz0ah89vv0126gsd0652pac9pi6fvpd
error: some substitutes for the outputs of derivation '/nix/store/k4a2l67vwlkgvwagzmbflbbiykgrb9bd-auto-update-0.1.6.drv' failed (usually happens due to networking issues); try '--fallback' to build derivation from source
```

**Comment by jkarni** [comment] 2022-12-22 20:31
On garnix machines, `nix store verify /nix/store/x3xa7h9wg6phf5a83is1vp4a663c61sq-auto-update-0.1.6` doesn't report any issues, and the only hash I find anywhere is the second. Not yet sure how you might be seeing this, but I'll continue investigating.

**Comment by jkarni** [comment] 2022-12-22 20:44
Ok, just a `nix build /nix/store/x3xa7h9wg6phf5a83is1vp4a663c61sq-auto-update-0.1.6` reproduces the issue for me.

**Comment by Conni2461** [comment] 2023-07-31 14:25
I know, saying we currently experiencing the same issue isn't usually not helpful but yeah, we currently experiencing the same issue :see_no_evil: 

Some context, we have a case study about using nix for scientific software and have a separate repo for this: https://github.com/precice/nix-packages

and several people experience this issue for different packages.

![image](https://github.com/garnix-io/issues/assets/15233006/e0a33998-7881-4fab-8ff5-81047660806e)

And here is the CI run: https://github.com/precice/nix-packages/runs/15483454890 

did anyone find a solution for this issue other than build from scratch with `--fallback`

**Comment by sellout** [comment] 2023-08-25 18:29
A similar issue elsewhere, with maybe some clues: https://discourse.nixos.org/t/error-hash-mismatch-importing-path/26353/4 – seemed to be due to a non-deterministic build that had been built in two places. The link to the fix for that package is broken, so here it is: https://github.com/NixOS/nixpkgs/pull/239230

Another case in `hydra-queue-runner`, with a PR that fixes it: https://github.com/NixOS/hydra/issues/816#issuecomment-724415640

The two cases are similar in that they involve the same package being built on two machines. It seems like the issue can happen even if the packages _are_ deterministic.

**Comment by jkarni** [comment] 2024-02-24 15:26
We haven't seen this in a while, so closing. If anyone comes across it again, please reopen!

**Closed as completed by jkarni** 2024-02-24 15:26 UTC
