### ISSUE TITLE
flake in non-standard location

### ISSUE THREAD

**Issue by Mic92** [garnix-io/issues#46] opened 2022-12-23 15:09 UTC
In some projects one might be not allowed a flake in the toplevel directory (i.e. political/policy reasons).
In our particular project we don't want to use the flake in the toplevel directory since we use unpinned nixpkgs.
Therefore it would be cool if we could specify in garnix.toml an alternative directory.

**Comment by sellout** [comment] 2023-01-27 22:02
Duplicate of #27.

**Comment by jkarni** [comment] 2023-02-02 10:04
Closing in favor of #27

**Closed as completed by jkarni** 2023-02-02 10:04 UTC
